import { createContext, useContext, useState, useCallback } from 'react'

export type Language = 'en' | 'hi' | 'pa'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType>({} as LanguageContextType)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

// ─── Translations ────────────────────────────────────────────────
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.dashboard": "Dashboard",
    "nav.emergency": "Emergency",
    "nav.maps": "Maps",
    "nav.quiz": "Quiz",
    "nav.games": "Games",
    "nav.profile": "Profile",
    "nav.settings": "Settings",
    "nav.signout": "Sign out",
    "nav.login": "Login",

    // Home
    "home.hero.title": "Be Prepared, Stay Safe with",
    "home.hero.brand": "Bandhu",
    "home.hero.subtitle": "Your trusted companion for disaster preparedness, emergency alerts, and community support. Together, we build resilient communities.",
    "home.hero.getStarted": "Get Started",
    "home.hero.emergency": "Emergency",
    "home.stats.peopleProtected": "People Protected",
    "home.stats.shelterLocations": "Shelter Locations",
    "home.stats.emergencySupport": "Emergency Support",
    "home.stats.userRating": "User Rating",
    "home.features.title": "Comprehensive Disaster Preparedness",
    "home.features.subtitle": "From emergency alerts to community support, Bandhu provides everything you need to stay prepared and protected.",
    "home.features.emergencyAlerts": "Emergency Alerts",
    "home.features.emergencyAlertsDesc": "Real-time notifications for disaster warnings and safety updates",
    "home.features.shelterMaps": "Shelter Maps",
    "home.features.shelterMapsDesc": "Find nearby emergency shelters and safe locations",
    "home.features.communitySupport": "Community Support",
    "home.features.communitySupportDesc": "Connect with local volunteers and support networks",
    "home.features.preparednessQuiz": "Preparedness Quiz",
    "home.features.preparednessQuizDesc": "Test your disaster preparedness knowledge",
    "home.cta.title": "Join the Bandhu Community Today",
    "home.cta.subtitle": "Connect with thousands of prepared citizens and build a safer, more resilient community together.",
    "home.cta.createAccount": "Create Your Account",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Your disaster preparedness overview",
    "dashboard.preparednessScore": "Preparedness Score",
    "dashboard.itemsCompleted": "items completed",
    "dashboard.activeAlerts": "Active Alerts",
    "dashboard.noRecentAlerts": "No recent alerts",
    "dashboard.nearbyShelters": "Nearby Shelters",
    "dashboard.within5km": "Within 5km radius",
    "dashboard.emergencyContacts": "Emergency Contacts",
    "dashboard.preparednessChecklist": "Preparedness Checklist",
    "dashboard.recentAlerts": "Recent Alerts",
    "dashboard.police": "Police",
    "dashboard.fire": "Fire",
    "dashboard.medical": "Medical",
    "dashboard.womenHelpline": "Women Helpline",
    "dashboard.emergencyKit": "Emergency Kit",
    "dashboard.familyPlan": "Family Plan",
    "dashboard.importantDocuments": "Important Documents",
    "dashboard.waterStorage": "Water Storage",
    "dashboard.foodSupplies": "Food Supplies",
    "dashboard.firstAidTraining": "First Aid Training",
    "dashboard.heavyRainWarning": "Heavy Rain Warning",
    "dashboard.earthquakeDrillReminder": "Earthquake Drill Reminder",
    "dashboard.yourArea": "Your Area",
    "dashboard.hoursAgo": "2 hours ago",
    "dashboard.dayAgo": "1 day ago",

    // Emergency
    "emergency.title": "Emergency Center",
    "emergency.subtitle": "Quick access to emergency services and active alerts",
    "emergency.medical": "Medical",
    "emergency.fire": "Fire",
    "emergency.police": "Police",
    "emergency.disaster": "Disaster",
    "emergency.activeAlerts": "Active Alerts",
    "emergency.alertDetails": "Alert Details",
    "emergency.recommendedActions": "Recommended Actions:",
    "emergency.quickSafetyTips": "Quick Safety Tips",
    "emergency.emergencySOS": "Emergency SOS",
    "emergency.sosButton": "EMERGENCY SOS",
    "emergency.sosHint": "Press and hold for 3 seconds to activate",
    "emergency.cycloneTitle": "Cyclone Alert - Prepare for Heavy Winds",
    "emergency.cycloneDesc": "Cyclone approaching coastal areas. Secure loose objects and stay indoors.",
    "emergency.cycloneType": "Weather Warning",
    "emergency.cycloneLocation": "Mumbai, Maharashtra",
    "emergency.cycloneTime": "Active now",
    "emergency.cycloneAction1": "Stay indoors",
    "emergency.cycloneAction2": "Secure windows",
    "emergency.cycloneAction3": "Stock water & food",
    "emergency.drillTitle": "Monthly Earthquake Preparedness Drill",
    "emergency.drillDesc": "Practice drop, cover, and hold on procedures with your family.",
    "emergency.drillType": "Earthquake Drill",
    "emergency.drillLocation": "Your Area",
    "emergency.drillTime": "Tomorrow 10:00 AM",
    "emergency.drillAction1": "Practice drill",
    "emergency.drillAction2": "Check emergency kit",
    "emergency.drillAction3": "Review evacuation plan",
    "emergency.tip1": "Keep emergency numbers saved in your phone",
    "emergency.tip2": "Maintain a 72-hour emergency kit",
    "emergency.tip3": "Know your nearest evacuation routes",
    "emergency.tip4": "Have a family communication plan",
    "emergency.tip5": "Keep important documents in waterproof bag",

    // Maps
    "maps.title": "Emergency Shelters & Maps",
    "maps.subtitle": "Find nearby emergency shelters and safe locations",
    "maps.searchPlaceholder": "Search shelters by name or location...",
    "maps.interactiveMap": "Interactive Map",
    "maps.mapSetup": "Map integration requires additional setup",
    "maps.viewFullMap": "View Full Map",
    "maps.shelterDetails": "Shelter Details",
    "maps.capacity": "Capacity",
    "maps.currentOccupancy": "Current Occupancy",
    "maps.availableFacilities": "Available Facilities",
    "maps.getDirections": "Get Directions",
    "maps.call": "Call",
    "maps.nearbyShelters": "Nearby Shelters",
    "maps.occupancy": "Occupancy",
    "maps.quickActions": "Quick Actions",
    "maps.findNearest": "Find Nearest Shelter",
    "maps.emergencyContacts": "Emergency Contacts",
    "maps.reportStatus": "Report Shelter Status",
    "maps.open": "Open",
    "maps.full": "Full",
    "maps.closed": "Closed",
    "maps.people": "people",

    // Quiz
    "quiz.title": "Disaster Preparedness Quiz",
    "quiz.subtitle": "Test your emergency preparedness knowledge",
    "quiz.question": "Question",
    "quiz.of": "of",
    "quiz.complete": "Complete",
    "quiz.previous": "Previous",
    "quiz.nextQuestion": "Next Question",
    "quiz.finishQuiz": "Finish Quiz",
    "quiz.results": "Quiz Results",
    "quiz.resultsSubtitle": "See how well you know disaster preparedness",
    "quiz.yourScore": "Your Score",
    "quiz.outOf": "out of",
    "quiz.correct": "correct",
    "quiz.excellent": "Excellent!",
    "quiz.good": "Good!",
    "quiz.keepLearning": "Keep Learning!",
    "quiz.takeAgain": "Take Quiz Again",

    // Games
    "games.title": "Preparedness Games",
    "games.subtitle": "Learn disaster preparedness through interactive games and challenges",
    "games.playGame": "Play Game",
    "games.yourProgress": "Your Progress",
    "games.overallProgress": "Overall Progress",
    "games.gamesPlayed": "Games Played",
    "games.totalScore": "Total Score",
    "games.achievements": "Achievements",
    "games.leaderboard": "Leaderboard",
    "games.pts": "pts",
    "games.completed": "completed",
    "games.emergencyResponse": "Emergency Response Simulator",
    "games.emergencyResponseDesc": "Practice making quick decisions during various disaster scenarios",
    "games.memoryGame": "Preparedness Memory Game",
    "games.memoryGameDesc": "Match emergency items with their uses in disaster situations",
    "games.evacuationPuzzle": "Evacuation Route Puzzle",
    "games.evacuationPuzzleDesc": "Navigate through buildings and find the safest evacuation routes",
    "games.timelineChallenge": "Disaster Timeline Challenge",
    "games.timelineChallengeDesc": "Put disaster response actions in the correct order under time pressure",
    "games.easy": "Easy",
    "games.medium": "Medium",
    "games.hard": "Hard",
    "games.firstResponder": "First Responder",
    "games.firstResponderDesc": "Complete your first game",
    "games.quickThinker": "Quick Thinker",
    "games.quickThinkerDesc": "Complete a game in under 5 minutes",
    "games.perfectScore": "Perfect Score",
    "games.perfectScoreDesc": "Score 100% in any game",
    "games.teamPlayer": "Team Player",
    "games.teamPlayerDesc": "Play 5 multiplayer games",
    "games.masterPreparer": "Master Preparer",
    "games.masterPreparerDesc": "Complete all games",

    // Login
    "login.welcome": "Welcome to Bandhu",
    "login.companion": "Your disaster preparedness companion",
    "login.tab.login": "Login",
    "login.tab.register": "Register",
    "login.signIn": "Sign In",
    "login.signInDesc": "Enter your credentials to access your account",
    "login.email": "Email",
    "login.emailPlaceholder": "Enter your email",
    "login.password": "Password",
    "login.passwordPlaceholder": "Enter your password",
    "login.signingIn": "Signing in...",
    "login.forgotPassword": "Forgot your password?",
    "login.createAccount": "Create Account",
    "login.createAccountDesc": "Join the Bandhu community for disaster preparedness",
    "login.firstName": "First Name",
    "login.firstNamePlaceholder": "First name",
    "login.lastName": "Last Name",
    "login.lastNamePlaceholder": "Last name",
    "login.phone": "Phone Number",
    "login.phonePlaceholder": "Enter your phone number",
    "login.createPassword": "Create a password",
    "login.confirmPassword": "Confirm Password",
    "login.confirmPasswordPlaceholder": "Confirm your password",
    "login.creatingAccount": "Creating account...",
    "login.backToHome": "← Back to Home",
    "login.loginFailed": "Login Failed",
    "login.invalidCredentials": "Invalid email or password",
    "login.welcomeBack": "Welcome back!",
    "login.loginSuccess": "You have successfully logged in.",
    "login.loginError": "Login Error",
    "login.somethingWrong": "Something went wrong. Please try again.",
    "login.registrationFailed": "Registration Failed",
    "login.failedToCreate": "Failed to create account",
    "login.registrationSuccess": "Registration Successful!",
    "login.checkEmail": "Please check your email to verify your account.",
    "login.registrationError": "Registration Error",
    "login.passwordMismatch": "Password Mismatch",
    "login.passwordsNoMatch": "Passwords do not match",
    "login.weakPassword": "Weak Password",
    "login.passwordMinLength": "Password must be at least 6 characters long",

    // NotFound
    "notFound.title": "404",
    "notFound.message": "Oops! Page not found",
    "notFound.returnHome": "Return to Home",
  },

  hi: {
    // Navbar
    "nav.home": "होम",
    "nav.dashboard": "डैशबोर्ड",
    "nav.emergency": "आपातकाल",
    "nav.maps": "मानचित्र",
    "nav.quiz": "प्रश्नोत्तरी",
    "nav.games": "खेल",
    "nav.profile": "प्रोफ़ाइल",
    "nav.settings": "सेटिंग्स",
    "nav.signout": "लॉग आउट",
    "nav.login": "लॉगिन",

    // Home
    "home.hero.title": "तैयार रहें, सुरक्षित रहें",
    "home.hero.brand": "बंधु",
    "home.hero.subtitle": "आपदा तैयारी, आपातकालीन अलर्ट और सामुदायिक सहायता के लिए आपका विश्वसनीय साथी। साथ मिलकर, हम लचीले समुदाय बनाते हैं।",
    "home.hero.getStarted": "शुरू करें",
    "home.hero.emergency": "आपातकाल",
    "home.stats.peopleProtected": "सुरक्षित लोग",
    "home.stats.shelterLocations": "आश्रय स्थान",
    "home.stats.emergencySupport": "आपातकालीन सहायता",
    "home.stats.userRating": "उपयोगकर्ता रेटिंग",
    "home.features.title": "व्यापक आपदा तैयारी",
    "home.features.subtitle": "आपातकालीन अलर्ट से लेकर सामुदायिक सहायता तक, बंधु आपको तैयार और सुरक्षित रहने के लिए सब कुछ प्रदान करता है।",
    "home.features.emergencyAlerts": "आपातकालीन अलर्ट",
    "home.features.emergencyAlertsDesc": "आपदा चेतावनियों और सुरक्षा अपडेट के लिए रीयल-टाइम सूचनाएं",
    "home.features.shelterMaps": "आश्रय मानचित्र",
    "home.features.shelterMapsDesc": "नज़दीकी आपातकालीन आश्रय और सुरक्षित स्थान खोजें",
    "home.features.communitySupport": "सामुदायिक सहायता",
    "home.features.communitySupportDesc": "स्थानीय स्वयंसेवकों और सहायता नेटवर्क से जुड़ें",
    "home.features.preparednessQuiz": "तैयारी प्रश्नोत्तरी",
    "home.features.preparednessQuizDesc": "अपनी आपदा तैयारी ज्ञान का परीक्षण करें",
    "home.cta.title": "आज ही बंधु समुदाय से जुड़ें",
    "home.cta.subtitle": "हजारों तैयार नागरिकों से जुड़ें और एक सुरक्षित, अधिक लचीला समुदाय बनाएं।",
    "home.cta.createAccount": "अपना खाता बनाएं",

    // Dashboard
    "dashboard.title": "डैशबोर्ड",
    "dashboard.subtitle": "आपकी आपदा तैयारी का अवलोकन",
    "dashboard.preparednessScore": "तैयारी स्कोर",
    "dashboard.itemsCompleted": "आइटम पूर्ण",
    "dashboard.activeAlerts": "सक्रिय अलर्ट",
    "dashboard.noRecentAlerts": "कोई हालिया अलर्ट नहीं",
    "dashboard.nearbyShelters": "नज़दीकी आश्रय",
    "dashboard.within5km": "5 किमी दायरे में",
    "dashboard.emergencyContacts": "आपातकालीन संपर्क",
    "dashboard.preparednessChecklist": "तैयारी चेकलिस्ट",
    "dashboard.recentAlerts": "हालिया अलर्ट",
    "dashboard.police": "पुलिस",
    "dashboard.fire": "अग्निशमन",
    "dashboard.medical": "चिकित्सा",
    "dashboard.womenHelpline": "महिला हेल्पलाइन",
    "dashboard.emergencyKit": "आपातकालीन किट",
    "dashboard.familyPlan": "पारिवारिक योजना",
    "dashboard.importantDocuments": "महत्वपूर्ण दस्तावेज़",
    "dashboard.waterStorage": "पानी भंडारण",
    "dashboard.foodSupplies": "खाद्य आपूर्ति",
    "dashboard.firstAidTraining": "प्राथमिक चिकित्सा प्रशिक्षण",
    "dashboard.heavyRainWarning": "भारी बारिश की चेतावनी",
    "dashboard.earthquakeDrillReminder": "भूकंप अभ्यास अनुस्मारक",
    "dashboard.yourArea": "आपका क्षेत्र",
    "dashboard.hoursAgo": "2 घंटे पहले",
    "dashboard.dayAgo": "1 दिन पहले",

    // Emergency
    "emergency.title": "आपातकालीन केंद्र",
    "emergency.subtitle": "आपातकालीन सेवाओं और सक्रिय अलर्ट तक त्वरित पहुंच",
    "emergency.medical": "चिकित्सा",
    "emergency.fire": "अग्निशमन",
    "emergency.police": "पुलिस",
    "emergency.disaster": "आपदा",
    "emergency.activeAlerts": "सक्रिय अलर्ट",
    "emergency.alertDetails": "अलर्ट विवरण",
    "emergency.recommendedActions": "अनुशंसित कार्रवाई:",
    "emergency.quickSafetyTips": "त्वरित सुरक्षा टिप्स",
    "emergency.emergencySOS": "आपातकालीन SOS",
    "emergency.sosButton": "आपातकालीन SOS",
    "emergency.sosHint": "सक्रिय करने के लिए 3 सेकंड तक दबाएं",
    "emergency.cycloneTitle": "चक्रवात अलर्ट - तेज़ हवाओं के लिए तैयार रहें",
    "emergency.cycloneDesc": "तटीय क्षेत्रों में चक्रवात आ रहा है। ढीली वस्तुओं को सुरक्षित करें और घर के अंदर रहें।",
    "emergency.cycloneType": "मौसम चेतावनी",
    "emergency.cycloneLocation": "मुंबई, महाराष्ट्र",
    "emergency.cycloneTime": "अभी सक्रिय",
    "emergency.cycloneAction1": "घर के अंदर रहें",
    "emergency.cycloneAction2": "खिड़कियां सुरक्षित करें",
    "emergency.cycloneAction3": "पानी और भोजन का भंडार करें",
    "emergency.drillTitle": "मासिक भूकंप तैयारी अभ्यास",
    "emergency.drillDesc": "अपने परिवार के साथ ड्रॉप, कवर और होल्ड ऑन प्रक्रियाओं का अभ्यास करें।",
    "emergency.drillType": "भूकंप अभ्यास",
    "emergency.drillLocation": "आपका क्षेत्र",
    "emergency.drillTime": "कल सुबह 10:00 बजे",
    "emergency.drillAction1": "अभ्यास करें",
    "emergency.drillAction2": "आपातकालीन किट जांचें",
    "emergency.drillAction3": "निकासी योजना की समीक्षा करें",
    "emergency.tip1": "आपातकालीन नंबर अपने फोन में सेव रखें",
    "emergency.tip2": "72 घंटे की आपातकालीन किट बनाए रखें",
    "emergency.tip3": "अपने निकटतम निकासी मार्ग जानें",
    "emergency.tip4": "पारिवारिक संचार योजना बनाएं",
    "emergency.tip5": "महत्वपूर्ण दस्तावेज़ वॉटरप्रूफ बैग में रखें",

    // Maps
    "maps.title": "आपातकालीन आश्रय और मानचित्र",
    "maps.subtitle": "नज़दीकी आपातकालीन आश्रय और सुरक्षित स्थान खोजें",
    "maps.searchPlaceholder": "नाम या स्थान से आश्रय खोजें...",
    "maps.interactiveMap": "इंटरैक्टिव मानचित्र",
    "maps.mapSetup": "मानचित्र एकीकरण के लिए अतिरिक्त सेटअप आवश्यक है",
    "maps.viewFullMap": "पूरा मानचित्र देखें",
    "maps.shelterDetails": "आश्रय विवरण",
    "maps.capacity": "क्षमता",
    "maps.currentOccupancy": "वर्तमान अधिभोग",
    "maps.availableFacilities": "उपलब्ध सुविधाएं",
    "maps.getDirections": "दिशा-निर्देश प्राप्त करें",
    "maps.call": "कॉल",
    "maps.nearbyShelters": "नज़दीकी आश्रय",
    "maps.occupancy": "अधिभोग",
    "maps.quickActions": "त्वरित कार्रवाई",
    "maps.findNearest": "निकटतम आश्रय खोजें",
    "maps.emergencyContacts": "आपातकालीन संपर्क",
    "maps.reportStatus": "आश्रय स्थिति रिपोर्ट करें",
    "maps.open": "खुला",
    "maps.full": "भरा हुआ",
    "maps.closed": "बंद",
    "maps.people": "लोग",

    // Quiz
    "quiz.title": "आपदा तैयारी प्रश्नोत्तरी",
    "quiz.subtitle": "अपनी आपातकालीन तैयारी ज्ञान का परीक्षण करें",
    "quiz.question": "प्रश्न",
    "quiz.of": "में से",
    "quiz.complete": "पूर्ण",
    "quiz.previous": "पिछला",
    "quiz.nextQuestion": "अगला प्रश्न",
    "quiz.finishQuiz": "प्रश्नोत्तरी समाप्त करें",
    "quiz.results": "प्रश्नोत्तरी परिणाम",
    "quiz.resultsSubtitle": "देखें कि आपदा तैयारी के बारे में आप कितना जानते हैं",
    "quiz.yourScore": "आपका स्कोर",
    "quiz.outOf": "में से",
    "quiz.correct": "सही",
    "quiz.excellent": "उत्कृष्ट!",
    "quiz.good": "अच्छा!",
    "quiz.keepLearning": "सीखते रहें!",
    "quiz.takeAgain": "फिर से प्रश्नोत्तरी लें",

    // Games
    "games.title": "तैयारी खेल",
    "games.subtitle": "इंटरैक्टिव खेलों और चुनौतियों के माध्यम से आपदा तैयारी सीखें",
    "games.playGame": "खेल शुरू करें",
    "games.yourProgress": "आपकी प्रगति",
    "games.overallProgress": "कुल प्रगति",
    "games.gamesPlayed": "खेले गए खेल",
    "games.totalScore": "कुल स्कोर",
    "games.achievements": "उपलब्धियां",
    "games.leaderboard": "लीडरबोर्ड",
    "games.pts": "अंक",
    "games.completed": "पूर्ण",
    "games.emergencyResponse": "आपातकालीन प्रतिक्रिया सिम्युलेटर",
    "games.emergencyResponseDesc": "विभिन्न आपदा परिदृश्यों में त्वरित निर्णय लेने का अभ्यास करें",
    "games.memoryGame": "तैयारी मेमोरी गेम",
    "games.memoryGameDesc": "आपातकालीन वस्तुओं को उनके उपयोग से मिलाएं",
    "games.evacuationPuzzle": "निकासी मार्ग पहेली",
    "games.evacuationPuzzleDesc": "इमारतों से गुजरें और सबसे सुरक्षित निकासी मार्ग खोजें",
    "games.timelineChallenge": "आपदा टाइमलाइन चुनौती",
    "games.timelineChallengeDesc": "समय दबाव में आपदा प्रतिक्रिया कार्यों को सही क्रम में रखें",
    "games.easy": "आसान",
    "games.medium": "मध्यम",
    "games.hard": "कठिन",
    "games.firstResponder": "पहला प्रतिक्रियाकर्ता",
    "games.firstResponderDesc": "अपना पहला खेल पूरा करें",
    "games.quickThinker": "तेज़ सोच",
    "games.quickThinkerDesc": "5 मिनट से कम में खेल पूरा करें",
    "games.perfectScore": "पूर्ण स्कोर",
    "games.perfectScoreDesc": "किसी भी खेल में 100% स्कोर करें",
    "games.teamPlayer": "टीम खिलाड़ी",
    "games.teamPlayerDesc": "5 मल्टीप्लेयर खेल खेलें",
    "games.masterPreparer": "मास्टर तैयारीकर्ता",
    "games.masterPreparerDesc": "सभी खेल पूरे करें",

    // Login
    "login.welcome": "बंधु में आपका स्वागत है",
    "login.companion": "आपकी आपदा तैयारी साथी",
    "login.tab.login": "लॉगिन",
    "login.tab.register": "पंजीकरण",
    "login.signIn": "साइन इन",
    "login.signInDesc": "अपने खाते तक पहुंचने के लिए अपने क्रेडेंशियल दर्ज करें",
    "login.email": "ईमेल",
    "login.emailPlaceholder": "अपना ईमेल दर्ज करें",
    "login.password": "पासवर्ड",
    "login.passwordPlaceholder": "अपना पासवर्ड दर्ज करें",
    "login.signingIn": "साइन इन हो रहा है...",
    "login.forgotPassword": "पासवर्ड भूल गए?",
    "login.createAccount": "खाता बनाएं",
    "login.createAccountDesc": "आपदा तैयारी के लिए बंधु समुदाय से जुड़ें",
    "login.firstName": "पहला नाम",
    "login.firstNamePlaceholder": "पहला नाम",
    "login.lastName": "अंतिम नाम",
    "login.lastNamePlaceholder": "अंतिम नाम",
    "login.phone": "फ़ोन नंबर",
    "login.phonePlaceholder": "अपना फ़ोन नंबर दर्ज करें",
    "login.createPassword": "पासवर्ड बनाएं",
    "login.confirmPassword": "पासवर्ड की पुष्टि करें",
    "login.confirmPasswordPlaceholder": "अपने पासवर्ड की पुष्टि करें",
    "login.creatingAccount": "खाता बनाया जा रहा है...",
    "login.backToHome": "← होम पर वापस जाएं",
    "login.loginFailed": "लॉगिन विफल",
    "login.invalidCredentials": "अमान्य ईमेल या पासवर्ड",
    "login.welcomeBack": "वापसी पर स्वागत!",
    "login.loginSuccess": "आपने सफलतापूर्वक लॉग इन किया है।",
    "login.loginError": "लॉगिन त्रुटि",
    "login.somethingWrong": "कुछ गलत हो गया। कृपया पुनः प्रयास करें।",
    "login.registrationFailed": "पंजीकरण विफल",
    "login.failedToCreate": "खाता बनाने में विफल",
    "login.registrationSuccess": "पंजीकरण सफल!",
    "login.checkEmail": "कृपया अपना खाता सत्यापित करने के लिए अपना ईमेल जांचें।",
    "login.registrationError": "पंजीकरण त्रुटि",
    "login.passwordMismatch": "पासवर्ड मेल नहीं खाता",
    "login.passwordsNoMatch": "पासवर्ड मेल नहीं खाते",
    "login.weakPassword": "कमज़ोर पासवर्ड",
    "login.passwordMinLength": "पासवर्ड कम से कम 6 अक्षर का होना चाहिए",

    // NotFound
    "notFound.title": "404",
    "notFound.message": "ओह! पेज नहीं मिला",
    "notFound.returnHome": "होम पर वापस जाएं",
  },

  pa: {
    // Navbar
    "nav.home": "ਹੋਮ",
    "nav.dashboard": "ਡੈਸ਼ਬੋਰਡ",
    "nav.emergency": "ਐਮਰਜੈਂਸੀ",
    "nav.maps": "ਨਕਸ਼ੇ",
    "nav.quiz": "ਕੁਇਜ਼",
    "nav.games": "ਖੇਡਾਂ",
    "nav.profile": "ਪ੍ਰੋਫਾਈਲ",
    "nav.settings": "ਸੈਟਿੰਗਾਂ",
    "nav.signout": "ਸਾਈਨ ਆਊਟ",
    "nav.login": "ਲੌਗਇਨ",

    // Home
    "home.hero.title": "ਤਿਆਰ ਰਹੋ, ਸੁਰੱਖਿਅਤ ਰਹੋ",
    "home.hero.brand": "ਬੰਧੂ",
    "home.hero.subtitle": "ਆਫ਼ਤ ਦੀ ਤਿਆਰੀ, ਐਮਰਜੈਂਸੀ ਅਲਰਟ ਅਤੇ ਕਮਿਊਨਿਟੀ ਸਹਾਇਤਾ ਲਈ ਤੁਹਾਡਾ ਭਰੋਸੇਮੰਦ ਸਾਥੀ। ਮਿਲ ਕੇ, ਅਸੀਂ ਮਜ਼ਬੂਤ ਭਾਈਚਾਰੇ ਬਣਾਉਂਦੇ ਹਾਂ।",
    "home.hero.getStarted": "ਸ਼ੁਰੂ ਕਰੋ",
    "home.hero.emergency": "ਐਮਰਜੈਂਸੀ",
    "home.stats.peopleProtected": "ਸੁਰੱਖਿਅਤ ਲੋਕ",
    "home.stats.shelterLocations": "ਸ਼ੈਲਟਰ ਟਿਕਾਣੇ",
    "home.stats.emergencySupport": "ਐਮਰਜੈਂਸੀ ਸਹਾਇਤਾ",
    "home.stats.userRating": "ਉਪਭੋਗਤਾ ਰੇਟਿੰਗ",
    "home.features.title": "ਵਿਆਪਕ ਆਫ਼ਤ ਤਿਆਰੀ",
    "home.features.subtitle": "ਐਮਰਜੈਂਸੀ ਅਲਰਟ ਤੋਂ ਲੈ ਕੇ ਕਮਿਊਨਿਟੀ ਸਹਾਇਤਾ ਤੱਕ, ਬੰਧੂ ਤੁਹਾਨੂੰ ਤਿਆਰ ਅਤੇ ਸੁਰੱਖਿਅਤ ਰਹਿਣ ਲਈ ਸਭ ਕੁਝ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ।",
    "home.features.emergencyAlerts": "ਐਮਰਜੈਂਸੀ ਅਲਰਟ",
    "home.features.emergencyAlertsDesc": "ਆਫ਼ਤ ਚੇਤਾਵਨੀਆਂ ਅਤੇ ਸੁਰੱਖਿਆ ਅਪਡੇਟਾਂ ਲਈ ਰੀਅਲ-ਟਾਈਮ ਸੂਚਨਾਵਾਂ",
    "home.features.shelterMaps": "ਸ਼ੈਲਟਰ ਨਕਸ਼ੇ",
    "home.features.shelterMapsDesc": "ਨੇੜੇ ਦੇ ਐਮਰਜੈਂਸੀ ਸ਼ੈਲਟਰ ਅਤੇ ਸੁਰੱਖਿਅਤ ਥਾਵਾਂ ਲੱਭੋ",
    "home.features.communitySupport": "ਕਮਿਊਨਿਟੀ ਸਹਾਇਤਾ",
    "home.features.communitySupportDesc": "ਸਥਾਨਕ ਵਲੰਟੀਅਰਾਂ ਅਤੇ ਸਹਾਇਤਾ ਨੈੱਟਵਰਕ ਨਾਲ ਜੁੜੋ",
    "home.features.preparednessQuiz": "ਤਿਆਰੀ ਕੁਇਜ਼",
    "home.features.preparednessQuizDesc": "ਆਪਣੀ ਆਫ਼ਤ ਤਿਆਰੀ ਗਿਆਨ ਦੀ ਜਾਂਚ ਕਰੋ",
    "home.cta.title": "ਅੱਜ ਹੀ ਬੰਧੂ ਭਾਈਚਾਰੇ ਨਾਲ ਜੁੜੋ",
    "home.cta.subtitle": "ਹਜ਼ਾਰਾਂ ਤਿਆਰ ਨਾਗਰਿਕਾਂ ਨਾਲ ਜੁੜੋ ਅਤੇ ਇੱਕ ਸੁਰੱਖਿਅਤ, ਮਜ਼ਬੂਤ ਭਾਈਚਾਰਾ ਬਣਾਓ।",
    "home.cta.createAccount": "ਆਪਣਾ ਖਾਤਾ ਬਣਾਓ",

    // Dashboard
    "dashboard.title": "ਡੈਸ਼ਬੋਰਡ",
    "dashboard.subtitle": "ਤੁਹਾਡੀ ਆਫ਼ਤ ਤਿਆਰੀ ਦੀ ਸੰਖੇਪ ਜਾਣਕਾਰੀ",
    "dashboard.preparednessScore": "ਤਿਆਰੀ ਸਕੋਰ",
    "dashboard.itemsCompleted": "ਆਈਟਮਾਂ ਪੂਰੀਆਂ",
    "dashboard.activeAlerts": "ਸਰਗਰਮ ਅਲਰਟ",
    "dashboard.noRecentAlerts": "ਕੋਈ ਹਾਲੀਆ ਅਲਰਟ ਨਹੀਂ",
    "dashboard.nearbyShelters": "ਨੇੜੇ ਦੇ ਸ਼ੈਲਟਰ",
    "dashboard.within5km": "5 ਕਿਲੋਮੀਟਰ ਦਾਇਰੇ ਵਿੱਚ",
    "dashboard.emergencyContacts": "ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ",
    "dashboard.preparednessChecklist": "ਤਿਆਰੀ ਚੈੱਕਲਿਸਟ",
    "dashboard.recentAlerts": "ਹਾਲੀਆ ਅਲਰਟ",
    "dashboard.police": "ਪੁਲਿਸ",
    "dashboard.fire": "ਅੱਗ ਬੁਝਾਊ",
    "dashboard.medical": "ਮੈਡੀਕਲ",
    "dashboard.womenHelpline": "ਔਰਤ ਹੈਲਪਲਾਈਨ",
    "dashboard.emergencyKit": "ਐਮਰਜੈਂਸੀ ਕਿੱਟ",
    "dashboard.familyPlan": "ਪਰਿਵਾਰਕ ਯੋਜਨਾ",
    "dashboard.importantDocuments": "ਮਹੱਤਵਪੂਰਨ ਦਸਤਾਵੇਜ਼",
    "dashboard.waterStorage": "ਪਾਣੀ ਸਟੋਰੇਜ",
    "dashboard.foodSupplies": "ਖੁਰਾਕ ਸਪਲਾਈ",
    "dashboard.firstAidTraining": "ਫਸਟ ਏਡ ਸਿਖਲਾਈ",
    "dashboard.heavyRainWarning": "ਭਾਰੀ ਮੀਂਹ ਦੀ ਚੇਤਾਵਨੀ",
    "dashboard.earthquakeDrillReminder": "ਭੂਚਾਲ ਅਭਿਆਸ ਯਾਦ-ਪੱਤਰ",
    "dashboard.yourArea": "ਤੁਹਾਡਾ ਖੇਤਰ",
    "dashboard.hoursAgo": "2 ਘੰਟੇ ਪਹਿਲਾਂ",
    "dashboard.dayAgo": "1 ਦਿਨ ਪਹਿਲਾਂ",

    // Emergency
    "emergency.title": "ਐਮਰਜੈਂਸੀ ਕੇਂਦਰ",
    "emergency.subtitle": "ਐਮਰਜੈਂਸੀ ਸੇਵਾਵਾਂ ਅਤੇ ਸਰਗਰਮ ਅਲਰਟ ਤੱਕ ਤੇਜ਼ ਪਹੁੰਚ",
    "emergency.medical": "ਮੈਡੀਕਲ",
    "emergency.fire": "ਅੱਗ ਬੁਝਾਊ",
    "emergency.police": "ਪੁਲਿਸ",
    "emergency.disaster": "ਆਫ਼ਤ",
    "emergency.activeAlerts": "ਸਰਗਰਮ ਅਲਰਟ",
    "emergency.alertDetails": "ਅਲਰਟ ਵੇਰਵੇ",
    "emergency.recommendedActions": "ਸਿਫ਼ਾਰਸ਼ੀ ਕਾਰਵਾਈਆਂ:",
    "emergency.quickSafetyTips": "ਤੇਜ਼ ਸੁਰੱਖਿਆ ਟਿੱਪਸ",
    "emergency.emergencySOS": "ਐਮਰਜੈਂਸੀ SOS",
    "emergency.sosButton": "ਐਮਰਜੈਂਸੀ SOS",
    "emergency.sosHint": "ਸਰਗਰਮ ਕਰਨ ਲਈ 3 ਸਕਿੰਟ ਦਬਾਓ",
    "emergency.cycloneTitle": "ਚੱਕਰਵਾਤ ਅਲਰਟ - ਤੇਜ਼ ਹਵਾਵਾਂ ਲਈ ਤਿਆਰ ਰਹੋ",
    "emergency.cycloneDesc": "ਤੱਟੀ ਖੇਤਰਾਂ ਵਿੱਚ ਚੱਕਰਵਾਤ ਆ ਰਿਹਾ ਹੈ। ਢਿੱਲੀਆਂ ਚੀਜ਼ਾਂ ਸੁਰੱਖਿਅਤ ਕਰੋ ਅਤੇ ਘਰ ਅੰਦਰ ਰਹੋ।",
    "emergency.cycloneType": "ਮੌਸਮ ਚੇਤਾਵਨੀ",
    "emergency.cycloneLocation": "ਮੁੰਬਈ, ਮਹਾਰਾਸ਼ਟਰ",
    "emergency.cycloneTime": "ਹੁਣੇ ਸਰਗਰਮ",
    "emergency.cycloneAction1": "ਘਰ ਅੰਦਰ ਰਹੋ",
    "emergency.cycloneAction2": "ਖਿੜਕੀਆਂ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    "emergency.cycloneAction3": "ਪਾਣੀ ਅਤੇ ਖਾਣਾ ਸਟੋਰ ਕਰੋ",
    "emergency.drillTitle": "ਮਹੀਨਾਵਾਰ ਭੂਚਾਲ ਤਿਆਰੀ ਅਭਿਆਸ",
    "emergency.drillDesc": "ਆਪਣੇ ਪਰਿਵਾਰ ਨਾਲ ਡ੍ਰੌਪ, ਕਵਰ ਅਤੇ ਹੋਲਡ ਆਨ ਪ੍ਰਕਿਰਿਆਵਾਂ ਦਾ ਅਭਿਆਸ ਕਰੋ।",
    "emergency.drillType": "ਭੂਚਾਲ ਅਭਿਆਸ",
    "emergency.drillLocation": "ਤੁਹਾਡਾ ਖੇਤਰ",
    "emergency.drillTime": "ਕੱਲ੍ਹ ਸਵੇਰੇ 10:00 ਵਜੇ",
    "emergency.drillAction1": "ਅਭਿਆਸ ਕਰੋ",
    "emergency.drillAction2": "ਐਮਰਜੈਂਸੀ ਕਿੱਟ ਚੈੱਕ ਕਰੋ",
    "emergency.drillAction3": "ਨਿਕਾਸੀ ਯੋਜਨਾ ਦੀ ਸਮੀਖਿਆ ਕਰੋ",
    "emergency.tip1": "ਐਮਰਜੈਂਸੀ ਨੰਬਰ ਆਪਣੇ ਫ਼ੋਨ ਵਿੱਚ ਸੇਵ ਰੱਖੋ",
    "emergency.tip2": "72 ਘੰਟੇ ਦੀ ਐਮਰਜੈਂਸੀ ਕਿੱਟ ਬਣਾ ਕੇ ਰੱਖੋ",
    "emergency.tip3": "ਆਪਣੇ ਨਜ਼ਦੀਕੀ ਨਿਕਾਸੀ ਰਸਤੇ ਜਾਣੋ",
    "emergency.tip4": "ਪਰਿਵਾਰਕ ਸੰਪਰਕ ਯੋਜਨਾ ਬਣਾਓ",
    "emergency.tip5": "ਮਹੱਤਵਪੂਰਨ ਦਸਤਾਵੇਜ਼ ਵਾਟਰਪਰੂਫ਼ ਬੈਗ ਵਿੱਚ ਰੱਖੋ",

    // Maps
    "maps.title": "ਐਮਰਜੈਂਸੀ ਸ਼ੈਲਟਰ ਅਤੇ ਨਕਸ਼ੇ",
    "maps.subtitle": "ਨੇੜੇ ਦੇ ਐਮਰਜੈਂਸੀ ਸ਼ੈਲਟਰ ਅਤੇ ਸੁਰੱਖਿਅਤ ਥਾਵਾਂ ਲੱਭੋ",
    "maps.searchPlaceholder": "ਨਾਮ ਜਾਂ ਟਿਕਾਣੇ ਦੁਆਰਾ ਸ਼ੈਲਟਰ ਖੋਜੋ...",
    "maps.interactiveMap": "ਇੰਟਰੈਕਟਿਵ ਨਕਸ਼ਾ",
    "maps.mapSetup": "ਨਕਸ਼ਾ ਏਕੀਕਰਣ ਲਈ ਵਾਧੂ ਸੈੱਟਅੱਪ ਲੋੜੀਂਦਾ ਹੈ",
    "maps.viewFullMap": "ਪੂਰਾ ਨਕਸ਼ਾ ਵੇਖੋ",
    "maps.shelterDetails": "ਸ਼ੈਲਟਰ ਵੇਰਵੇ",
    "maps.capacity": "ਸਮਰੱਥਾ",
    "maps.currentOccupancy": "ਮੌਜੂਦਾ ਭਰਤੀ",
    "maps.availableFacilities": "ਉਪਲਬਧ ਸੁਵਿਧਾਵਾਂ",
    "maps.getDirections": "ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼ ਲਓ",
    "maps.call": "ਕਾਲ",
    "maps.nearbyShelters": "ਨੇੜੇ ਦੇ ਸ਼ੈਲਟਰ",
    "maps.occupancy": "ਭਰਤੀ",
    "maps.quickActions": "ਤੇਜ਼ ਕਾਰਵਾਈਆਂ",
    "maps.findNearest": "ਨਜ਼ਦੀਕੀ ਸ਼ੈਲਟਰ ਲੱਭੋ",
    "maps.emergencyContacts": "ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ",
    "maps.reportStatus": "ਸ਼ੈਲਟਰ ਸਥਿਤੀ ਰਿਪੋਰਟ ਕਰੋ",
    "maps.open": "ਖੁੱਲ੍ਹਾ",
    "maps.full": "ਭਰਿਆ",
    "maps.closed": "ਬੰਦ",
    "maps.people": "ਲੋਕ",

    // Quiz
    "quiz.title": "ਆਫ਼ਤ ਤਿਆਰੀ ਕੁਇਜ਼",
    "quiz.subtitle": "ਆਪਣੀ ਐਮਰਜੈਂਸੀ ਤਿਆਰੀ ਗਿਆਨ ਦੀ ਜਾਂਚ ਕਰੋ",
    "quiz.question": "ਸਵਾਲ",
    "quiz.of": "ਵਿੱਚੋਂ",
    "quiz.complete": "ਪੂਰਾ",
    "quiz.previous": "ਪਿਛਲਾ",
    "quiz.nextQuestion": "ਅਗਲਾ ਸਵਾਲ",
    "quiz.finishQuiz": "ਕੁਇਜ਼ ਖ਼ਤਮ ਕਰੋ",
    "quiz.results": "ਕੁਇਜ਼ ਨਤੀਜੇ",
    "quiz.resultsSubtitle": "ਵੇਖੋ ਕਿ ਤੁਸੀਂ ਆਫ਼ਤ ਤਿਆਰੀ ਬਾਰੇ ਕਿੰਨਾ ਜਾਣਦੇ ਹੋ",
    "quiz.yourScore": "ਤੁਹਾਡਾ ਸਕੋਰ",
    "quiz.outOf": "ਵਿੱਚੋਂ",
    "quiz.correct": "ਸਹੀ",
    "quiz.excellent": "ਸ਼ਾਨਦਾਰ!",
    "quiz.good": "ਵਧੀਆ!",
    "quiz.keepLearning": "ਸਿੱਖਦੇ ਰਹੋ!",
    "quiz.takeAgain": "ਦੁਬਾਰਾ ਕੁਇਜ਼ ਲਓ",

    // Games
    "games.title": "ਤਿਆਰੀ ਖੇਡਾਂ",
    "games.subtitle": "ਇੰਟਰੈਕਟਿਵ ਖੇਡਾਂ ਅਤੇ ਚੁਣੌਤੀਆਂ ਰਾਹੀਂ ਆਫ਼ਤ ਤਿਆਰੀ ਸਿੱਖੋ",
    "games.playGame": "ਖੇਡ ਸ਼ੁਰੂ ਕਰੋ",
    "games.yourProgress": "ਤੁਹਾਡੀ ਤਰੱਕੀ",
    "games.overallProgress": "ਕੁੱਲ ਤਰੱਕੀ",
    "games.gamesPlayed": "ਖੇਡੀਆਂ ਗਈਆਂ ਖੇਡਾਂ",
    "games.totalScore": "ਕੁੱਲ ਸਕੋਰ",
    "games.achievements": "ਪ੍ਰਾਪਤੀਆਂ",
    "games.leaderboard": "ਲੀਡਰਬੋਰਡ",
    "games.pts": "ਅੰਕ",
    "games.completed": "ਪੂਰਾ",
    "games.emergencyResponse": "ਐਮਰਜੈਂਸੀ ਜਵਾਬ ਸਿਮੂਲੇਟਰ",
    "games.emergencyResponseDesc": "ਵੱਖ-ਵੱਖ ਆਫ਼ਤ ਹਾਲਾਤਾਂ ਵਿੱਚ ਤੇਜ਼ ਫ਼ੈਸਲੇ ਲੈਣ ਦਾ ਅਭਿਆਸ ਕਰੋ",
    "games.memoryGame": "ਤਿਆਰੀ ਮੈਮੋਰੀ ਗੇਮ",
    "games.memoryGameDesc": "ਐਮਰਜੈਂਸੀ ਚੀਜ਼ਾਂ ਨੂੰ ਉਨ੍ਹਾਂ ਦੇ ਉਪਯੋਗ ਨਾਲ ਮਿਲਾਓ",
    "games.evacuationPuzzle": "ਨਿਕਾਸੀ ਰਸਤਾ ਪਹੇਲੀ",
    "games.evacuationPuzzleDesc": "ਇਮਾਰਤਾਂ ਵਿੱਚੋਂ ਲੰਘੋ ਅਤੇ ਸਭ ਤੋਂ ਸੁਰੱਖਿਅਤ ਨਿਕਾਸੀ ਰਸਤੇ ਲੱਭੋ",
    "games.timelineChallenge": "ਆਫ਼ਤ ਟਾਈਮਲਾਈਨ ਚੁਣੌਤੀ",
    "games.timelineChallengeDesc": "ਸਮੇਂ ਦੇ ਦਬਾਅ ਹੇਠ ਆਫ਼ਤ ਜਵਾਬ ਕਾਰਵਾਈਆਂ ਨੂੰ ਸਹੀ ਕ੍ਰਮ ਵਿੱਚ ਰੱਖੋ",
    "games.easy": "ਆਸਾਨ",
    "games.medium": "ਦਰਮਿਆਨਾ",
    "games.hard": "ਔਖਾ",
    "games.firstResponder": "ਪਹਿਲਾ ਜਵਾਬਦਾਤਾ",
    "games.firstResponderDesc": "ਆਪਣੀ ਪਹਿਲੀ ਖੇਡ ਪੂਰੀ ਕਰੋ",
    "games.quickThinker": "ਤੇਜ਼ ਸੋਚ",
    "games.quickThinkerDesc": "5 ਮਿੰਟ ਤੋਂ ਘੱਟ ਵਿੱਚ ਖੇਡ ਪੂਰੀ ਕਰੋ",
    "games.perfectScore": "ਪੂਰਾ ਸਕੋਰ",
    "games.perfectScoreDesc": "ਕਿਸੇ ਵੀ ਖੇਡ ਵਿੱਚ 100% ਸਕੋਰ ਕਰੋ",
    "games.teamPlayer": "ਟੀਮ ਖਿਡਾਰੀ",
    "games.teamPlayerDesc": "5 ਮਲਟੀਪਲੇਅਰ ਖੇਡਾਂ ਖੇਡੋ",
    "games.masterPreparer": "ਮਾਸਟਰ ਤਿਆਰੀਕਰਤਾ",
    "games.masterPreparerDesc": "ਸਾਰੀਆਂ ਖੇਡਾਂ ਪੂਰੀਆਂ ਕਰੋ",

    // Login
    "login.welcome": "ਬੰਧੂ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ",
    "login.companion": "ਤੁਹਾਡਾ ਆਫ਼ਤ ਤਿਆਰੀ ਸਾਥੀ",
    "login.tab.login": "ਲੌਗਇਨ",
    "login.tab.register": "ਰਜਿਸਟਰ",
    "login.signIn": "ਸਾਈਨ ਇਨ",
    "login.signInDesc": "ਆਪਣੇ ਖਾਤੇ ਤੱਕ ਪਹੁੰਚਣ ਲਈ ਆਪਣੇ ਕ੍ਰੈਡੈਂਸ਼ੀਅਲ ਦਰਜ ਕਰੋ",
    "login.email": "ਈਮੇਲ",
    "login.emailPlaceholder": "ਆਪਣੀ ਈਮੇਲ ਦਰਜ ਕਰੋ",
    "login.password": "ਪਾਸਵਰਡ",
    "login.passwordPlaceholder": "ਆਪਣਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ",
    "login.signingIn": "ਸਾਈਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ...",
    "login.forgotPassword": "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?",
    "login.createAccount": "ਖਾਤਾ ਬਣਾਓ",
    "login.createAccountDesc": "ਆਫ਼ਤ ਤਿਆਰੀ ਲਈ ਬੰਧੂ ਭਾਈਚਾਰੇ ਨਾਲ ਜੁੜੋ",
    "login.firstName": "ਪਹਿਲਾ ਨਾਮ",
    "login.firstNamePlaceholder": "ਪਹਿਲਾ ਨਾਮ",
    "login.lastName": "ਆਖ਼ਰੀ ਨਾਮ",
    "login.lastNamePlaceholder": "ਆਖ਼ਰੀ ਨਾਮ",
    "login.phone": "ਫ਼ੋਨ ਨੰਬਰ",
    "login.phonePlaceholder": "ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ",
    "login.createPassword": "ਪਾਸਵਰਡ ਬਣਾਓ",
    "login.confirmPassword": "ਪਾਸਵਰਡ ਪੁਸ਼ਟੀ ਕਰੋ",
    "login.confirmPasswordPlaceholder": "ਆਪਣੇ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    "login.creatingAccount": "ਖਾਤਾ ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...",
    "login.backToHome": "← ਹੋਮ ਤੇ ਵਾਪਸ ਜਾਓ",
    "login.loginFailed": "ਲੌਗਇਨ ਅਸਫ਼ਲ",
    "login.invalidCredentials": "ਅਵੈਧ ਈਮੇਲ ਜਾਂ ਪਾਸਵਰਡ",
    "login.welcomeBack": "ਵਾਪਸੀ ਤੇ ਸੁਆਗਤ!",
    "login.loginSuccess": "ਤੁਸੀਂ ਸਫ਼ਲਤਾਪੂਰਵਕ ਲੌਗਇਨ ਕੀਤਾ ਹੈ।",
    "login.loginError": "ਲੌਗਇਨ ਗਲਤੀ",
    "login.somethingWrong": "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "login.registrationFailed": "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਅਸਫ਼ਲ",
    "login.failedToCreate": "ਖਾਤਾ ਬਣਾਉਣ ਵਿੱਚ ਅਸਫ਼ਲ",
    "login.registrationSuccess": "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਸਫ਼ਲ!",
    "login.checkEmail": "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਖਾਤਾ ਪੁਸ਼ਟੀ ਕਰਨ ਲਈ ਆਪਣੀ ਈਮੇਲ ਚੈੱਕ ਕਰੋ।",
    "login.registrationError": "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਗਲਤੀ",
    "login.passwordMismatch": "ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦਾ",
    "login.passwordsNoMatch": "ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ",
    "login.weakPassword": "ਕਮਜ਼ੋਰ ਪਾਸਵਰਡ",
    "login.passwordMinLength": "ਪਾਸਵਰਡ ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ",

    // NotFound
    "notFound.title": "404",
    "notFound.message": "ਓ! ਪੰਨਾ ਨਹੀਂ ਮਿਲਿਆ",
    "notFound.returnHome": "ਹੋਮ ਤੇ ਵਾਪਸ ਜਾਓ",
  },
}

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('bandhu_language')
    return (saved as Language) || 'en'
  })

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('bandhu_language', lang)
  }, [])

  const t = useCallback((key: string): string => {
    return translations[language][key] || translations['en'][key] || key
  }, [language])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
